# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-agency

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Nueva Vida One Reviews
email      : nueva-vida-one-reviews # this is also the email contact forms will go to
description: ""
author     : nueva-vida-one-reviews
# logo:     #optional, defaults to site title
  # path: 
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: # Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

####################
# Mine, additional

timezone: UTC

# permalink: /:title/ # same as in https://timdeschryver.dev/blog/how-to-test-your-csharp-web-api
permalink: /:year/:month/:day/:title/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      # type: posts
    values:
      layout: page
      # read_time: true